apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nodejs-argocicd"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:"shujaahmedi2l/nodejs-argocicd".git
    targetRevision: main
    path: helm/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-postgres-ahjquw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
