name: Nodejs PostgreSQL Image
on:
  push:
    branches: ['master']
    paths-ignore:
      - 'helm/**'
      - 'ecr/**'
jobs:
  node_project:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull & Push changes to repository - onexidp-gitops
        run: |
          sudo cp argo-ci-cd/${{ secrets.ARGO_CI_CD_YAML_NAME }} /tmp/${{ secrets.ARGO_CI_CD_YAML_NAME }}
          cd /tmp
          sudo git clone https://${{ secrets.REPO_TOKEN }}@github.com/robotfree/onexidp-gitops.git main
          ls -la
          sudo cp /tmp/${{ secrets.ARGO_CI_CD_YAML_NAME }} /tmp/main/onexidp/apps/${{ secrets.ARGO_CI_CD_YAML_NAME }}
          cd main
          ls -la
          sudo git add .
          sudo git commit -m "Updating apps/${{ secrets.ARGO_CI_CD_YAML_NAME }} file"
          sudo git push https://${{ secrets.REPO_TOKEN }}@github.com/robotfree/onexidp-gitops.git main

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Updating version number
        run: |
          cd helm
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
